"""Sync recipe.yaml from DESCRIPTION."""

import re
import sys
from pathlib import Path

JUPYTERLITE_DIR = Path(__file__).resolve().parent.parent
REPO_ROOT = JUPYTERLITE_DIR.parent
DESCRIPTION_PATH = REPO_ROOT / "DESCRIPTION"
RECIPE_PATH = JUPYTERLITE_DIR / "recipe.yaml"

# Packages included with r-base rather than published as separate Conda packages.
# Keep this list to R's base-priority packages; recommended packages can have
# their own Conda packages and should still be resolved when explicitly imported.
BASE_R_PACKAGES = {
    "base",
    "compiler",
    "datasets",
    "graphics",
    "grDevices",
    "grid",
    "methods",
    "parallel",
    "splines",
    "stats",
    "stats4",
    "tcltk",
    "tools",
    "utils",
}

LICENSE_TO_SPDX = {
    "AGPL (>= 3)": "AGPL-3.0-or-later",
    "GPL (>= 3)": "GPL-3.0-or-later",
}


def parse_description():
    """Parse release metadata and Imports from DESCRIPTION (DCF format)."""
    text = DESCRIPTION_PATH.read_text()

    version_match = re.search(r"^Version:\s*(.+)$", text, re.MULTILINE)
    if not version_match:
        print("ERROR: Could not find Version in DESCRIPTION", file=sys.stderr)
        sys.exit(1)
    version = version_match.group(1).strip()

    license_match = re.search(r"^License:\s*(.+)$", text, re.MULTILINE)
    if not license_match:
        print("ERROR: Could not find License in DESCRIPTION", file=sys.stderr)
        sys.exit(1)
    r_license = license_match.group(1).strip()
    if r_license not in LICENSE_TO_SPDX:
        print(
            f"ERROR: No SPDX mapping for DESCRIPTION license: {r_license}",
            file=sys.stderr,
        )
        sys.exit(1)
    spdx_license = LICENSE_TO_SPDX[r_license]

    depends_match = re.search(
        r"^Depends:\s*\n?(.*?)(?=^[A-Za-z]|\Z)", text, re.MULTILINE | re.DOTALL
    )
    r_version = "3.6"
    if depends_match:
        r_match = re.search(r"R\s*\(\s*>=\s*([\d.]+)\s*\)", depends_match.group(1))
        if r_match:
            r_version = r_match.group(1)

    imports_match = re.search(
        r"^Imports:\s*\n?(.*?)(?=^[A-Za-z]|\Z)", text, re.MULTILINE | re.DOTALL
    )
    if not imports_match:
        print("ERROR: Could not find Imports in DESCRIPTION", file=sys.stderr)
        sys.exit(1)

    imports_text = "Imports: " + imports_match.group(1)
    deps = [
        (name, ver) for name, ver in parse_deps(imports_text)
        if name not in BASE_R_PACKAGES
    ]
    return version, r_version, spdx_license, deps


def parse_deps(text):
    """Parse dependency entries like 'cli (>= 3.2.0)' from a DCF field."""
    text = re.sub(r"^[A-Za-z]+:\s*", "", text).strip()
    entries = [e.strip() for e in re.split(r",(?![^(]*\))", text) if e.strip()]

    deps = []
    for entry in entries:
        match = re.match(r"(\S+)\s*(?:\(([^)]+)\))?", entry)
        if match:
            deps.append((match.group(1), match.group(2)))
    return deps


def r_to_conda_name(r_name):
    """Convert R package name to conda package name."""
    return f"r-{r_name.lower()}"


def format_conda_version(constraint):
    """Convert R version constraint to conda format."""
    if not constraint:
        return ""
    return re.sub(r"\s+", "", constraint)


def generate_recipe(version, r_version, spdx_license, deps):
    """Generate recipe.yaml content."""
    run_deps = []
    for name, constraint in deps:
        conda_name = r_to_conda_name(name)
        conda_ver = format_conda_version(constraint)
        if conda_ver:
            run_deps.append(f"    - {conda_name} {conda_ver}")
        else:
            run_deps.append(f"    - {conda_name}")

    run_deps_str = "\n".join(run_deps)

    # rattler-build resolves ${{ r_base }} from the variant config (.r-version.yaml)
    r_base_pin = "${{ r_base }}"

    return f"""\
# AUTO-GENERATED by scripts/sync-recipe.py — do not edit manually.
# Run `pixi run sync-recipe` to regenerate from DESCRIPTION.

package:
  name: r-coursekata
  version: "{version}"

source:
  path: ..

build:
  noarch: generic
  script:
    - mkdir -p $PREFIX/lib/R/library
    - R CMD INSTALL --use-vanilla --no-test-load --library=$PREFIX/lib/R/library .

requirements:
  host:
    - r-base =={r_base_pin}
{run_deps_str}
  run:
    - r-base >={r_version}
{run_deps_str}

about:
  homepage: https://github.com/coursekata/coursekata-r
  summary: Packages and Functions for CourseKata Courses
  license: {spdx_license}
"""


def write_if_changed(path, content):
    """Write content to path only if it differs from current content."""
    if path.exists() and path.read_text() == content:
        return False
    path.write_text(content)
    return True


def main():
    version, r_version, spdx_license, deps = parse_description()

    recipe_content = generate_recipe(version, r_version, spdx_license, deps)
    if write_if_changed(RECIPE_PATH, recipe_content):
        print(f"Updated {RECIPE_PATH.relative_to(JUPYTERLITE_DIR)} ({len(deps)} deps, version {version})")


if __name__ == "__main__":
    main()
