[workspace]
name = "coursekata-demo-wasm"
channels = [
    "../.channel",
    "https://repo.prefix.dev/emscripten-forge-4x",
    "conda-forge",
]
platforms = ["emscripten-wasm32"]

[dependencies]
xeus-r = "*"
r-coursekata = "*"
