test_that("gf_square_resid_fun returns a ggplot with polygon layer", {
  df <- data.frame(X = 1:10, Y = 2 + 3 * (1:10) + c(1, -1, 2, -2, 0, 1, -1, 0, 2, -2))
  my_fun <- function(x) 2 + 3 * x
  p <- gf_point(Y ~ X, data = df) %>%
    gf_function(my_fun)

  result <- suppressMessages(gf_square_resid_fun(p, my_fun))
  expect_s3_class(result, "ggplot")

  i <- layer_index(result, "square_resid")
  expect_true(inherits(result$layers[[i]]$geom, "GeomSquareResid"))
  expect_equal(nrow(ggplot2::ggplot_build(result)$data[[i]]), nrow(df))
})

test_that("gf_square_resid_fun respects aspect ratio parameter", {
  df <- data.frame(X = 1:10, Y = 1:10 + c(1, -1, 2, -2, 0, 1, -1, 0, 2, -2))
  my_fun <- function(x) x
  p <- gf_point(Y ~ X, data = df)

  result_default <- suppressMessages(gf_square_resid_fun(p, my_fun))
  result_custom <- suppressMessages(gf_square_resid_fun(p, my_fun, aspect = 1))
  expect_s3_class(result_default, "ggplot")
  expect_s3_class(result_custom, "ggplot")
})

test_that("gf_square_resid_fun passes additional aesthetics", {
  df <- data.frame(X = 1:10, Y = 1:10)
  p <- gf_point(Y ~ X, data = df)
  my_fun <- function(x) x

  result <- suppressMessages(
    gf_square_resid_fun(p, my_fun, color = "blue", fill = "lightblue")
  )
  expect_s3_class(result, "ggplot")
})

test_that("gf_square_resid_fun reads an x mapped on the plot's first layer", {
  df <- data.frame(X = 1:10, Y = 2 + 3 * (1:10))
  p <- ggplot2::ggplot(df) + ggplot2::geom_point(ggplot2::aes(x = X, y = Y))
  r <- suppressMessages(gf_square_resid_fun(p, function(x) x + 1))
  drawn <- ggplot2::ggplot_build(r)$data[[layer_index(r, "square_resid")]]

  expect_equal(drawn$yend, df$X + 1)
})

test_that("gf_square_resid_fun snapshot", {
  skip_if_not_installed("vdiffr")
  df <- data.frame(X = 1:10, Y = c(3, 5, 8, 10, 14, 16, 20, 22, 25, 28))
  my_fun <- function(x) 1 + 3 * x
  p <- gf_point(Y ~ X, data = df) %>%
    gf_function(my_fun)

  suppressMessages(gf_square_resid_fun(p, my_fun, color = "blue")) %>%
    expect_doppelganger("gf_square_resid_fun-basic")
})


# gf_square_resid_fun() is generated by ggformula::layer_factory() now, like
# every other layer in this package. These are the contract.

test_that("a function given positionally lands where a function given by name does", {
  df <- data.frame(X = 1:10, Y = 2 + 3 * (1:10))
  p <- gf_point(Y ~ X, data = df)
  my_fun <- function(x) 2 + 3 * x

  positional <- suppressMessages(gf_square_resid_fun(p, my_fun))
  named <- suppressMessages(gf_square_resid_fun(p, fun = my_fun))

  expect_equal(layer_index(positional, "square_resid"), 2L)
  expect_equal(layer_index(named, "square_resid"), 2L)
  expect_equal(
    ggplot2::ggplot_build(positional)$data[[2]],
    ggplot2::ggplot_build(named)$data[[2]]
  )
})

test_that("a non-function is refused as a function, whichever way it is written", {
  p <- gf_point(Thumb ~ Height, data = Fingers)
  model <- lm(Thumb ~ Height, data = Fingers)

  for (bad in list(model, Thumb ~ Height, 3, "nope")) {
    expect_error(suppressMessages(gf_square_resid_fun(p, bad)), 'could not find function "fun"')
    expect_error(
      suppressMessages(gf_square_resid_fun(p, fun = bad)), 'could not find function "fun"'
    )
  }
})

test_that("a plot with no function is refused under this function's own name", {
  p <- gf_point(Thumb ~ Height, data = Fingers)
  expect_error(
    suppressMessages(gf_square_resid_fun(fun = function(x) x)),
    "`gf_square_resid_fun\\(\\)` needs to be layered on top of a plot"
  )
  expect_error(
    suppressMessages(gf_square_resid_fun(p)),
    "`gf_square_resid_fun\\(\\)` needs to be told which function"
  )
})

test_that("the plot is the first argument, and a name for it is not one", {
  # `plot` was the released spelling of the first argument. It is now `object`,
  # the name every generated ggformula layer uses, so `plot =` is an unknown
  # name like any other and ggformula discards it -- which leaves no plot, and
  # the refusal a caller sees is the one for that
  p <- gf_point(Thumb ~ Height, data = Fingers)
  f <- function(x) x + 20

  expect_error(gf_square_resid_fun(plot = p, fun = f), "layered on top of a plot")
  expect_no_error(suppressMessages(gf_square_resid_fun(object = p, fun = f)))
})

test_that("a bare call prints the layer's own help instead of drawing", {
  expect_message(bare <- gf_square_resid_fun(), "does not require a formula")
  expect_null(bare)

  p <- gf_point(Thumb ~ Height, data = Fingers)
  expect_message(asked <- gf_square_resid_fun(p, show.help = TRUE), "key attributes")
  expect_null(asked)
})

test_that("the labelling arguments every ggformula layer takes reach the plot", {
  p <- gf_point(Thumb ~ Height, data = Fingers) %>%
    gf_square_resid_fun(function(x) x, title = "TT", xlab = "XX", ylab = "YY")

  expect_equal(p$labels$title, "TT")
  expect_equal(p$labels$x, "XX")
  expect_equal(p$labels$y, "YY")
})

test_that("a squared residual draws with its own geom, stat and position whatever is asked for", {
  p <- gf_point(Thumb ~ Height, data = Fingers)

  expect_no_warning(
    asked <- suppressMessages(
      gf_square_resid_fun(
        p, function(x) x, geom = "polygon", stat = "identity", position = "dodge"
      )
    )
  )
  layer <- asked$layers[[layer_index(asked, "square_resid")]]

  expect_s3_class(layer$geom, "GeomSquareResid")
  expect_s3_class(layer$stat, "StatResid")
  # an unjittered plot needs no offset, so the layer declares identity;
  # what matters is that the caller's `position =` did not reach it
  expect_s3_class(layer$position, "PositionIdentity")
  expect_false(isTRUE(layer$inherit.aes))
})

test_that("a stray positional argument gets ggformula's own refusal, not one of ours", {
  # the released signature was `gf_square_resid_fun(plot, fun, aspect = 4/6,
  # alpha = 0.1, ...)`, and both positions really worked until this conversion
  p <- gf_point(Thumb ~ Height, data = Fingers)

  expect_error(gf_square_resid_fun(p, function(x) x, 0.5), "must be a <data.frame>")
  expect_error(gf_square_resid_fun(p, function(x) x, 0.5, 0.3), "must be a <data.frame>")

  expect_no_error(suppressMessages(gf_square_resid_fun(p, function(x) x, , 0.3)))
  expect_no_error(suppressMessages(gf_square_resid_fun(p, function(x) x, nonesuch = 1)))
})

test_that("aspect sizes the square as a geom parameter and alpha shades it as an aesthetic", {
  # they travel by different routes and both have to arrive: `aspect` is a
  # `draw_panel()` formal, so it is a geom parameter; `alpha` is an aesthetic
  p <- gf_point(Thumb ~ Height, data = Fingers)
  fun <- function(x) x + 20
  side <- function(plot) {
    grob <- ggplot2::layer_grob(plot, layer_index(plot, "square_resid"))[[1]]
    mean(tapply(as.numeric(grob$x), grob$id, function(z) diff(range(z))))
  }

  plain <- suppressMessages(gf_square_resid_fun(p, fun))
  square <- suppressMessages(gf_square_resid_fun(p, fun, aspect = 1))
  faded <- suppressMessages(gf_square_resid_fun(p, fun, alpha = 0.7))

  expect_equal(plain$layers[[2]]$geom_params$aspect, 4 / 6)
  expect_equal(square$layers[[2]]$geom_params$aspect, 1)
  expect_equal(side(plain), side(square) * 4 / 6)

  expect_equal(plain$layers[[2]]$aes_params$alpha, 0.1)
  expect_equal(faded$layers[[2]]$aes_params$alpha, 0.7)
  expect_null(plain$layers[[2]]$geom_params$alpha)
})

test_that("a square does not inherit a mapped color but a segment does", {
  # a square is a filled region in the geom's own colors: inheriting a mapped
  # color outlines every square in the color of the group it measures
  p <- gf_point(Thumb ~ Height, color = ~Sex, data = Fingers)
  fun <- function(x) x + 20
  built <- function(plot, tag) ggplot2::ggplot_build(plot)$data[[layer_index(plot, tag)]]

  square <- suppressMessages(gf_square_resid_fun(p, fun))
  segment <- suppressMessages(gf_resid_fun(p, fun))

  expect_true(all(is.na(built(square, "square_resid")$colour)))
  expect_length(unique(built(segment, "resid")$colour), 2)
})

test_that("the function is called on the x values the plot draws", {
  p <- gf_point(Thumb ~ log(Height), data = Fingers)
  r <- suppressMessages(gf_square_resid_fun(p, function(x) x * 14))
  drawn <- ggplot2::ggplot_build(r)$data[[layer_index(r, "square_resid")]]

  expect_equal(drawn$yend, log(Fingers$Height) * 14)
})

test_that("the plot is reported before the function is ever called", {
  boom <- function(x) stop("this function cannot be called")

  expect_error(
    suppressMessages(gf_square_resid_fun(gf_histogram(~Thumb, data = Fingers), boom)),
    "A residual needs both an x and a y on the plot"
  )
})

test_that("a function that predicts nothing draws nothing rather than failing", {
  # every prediction NA is where GeomSquareResid returns a zeroGrob
  p <- gf_point(Thumb ~ Height, data = Fingers)
  drawn <- suppressMessages(gf_square_resid_fun(p, function(x) NA_real_))

  expect_s3_class(
    ggplot2::layer_grob(drawn, layer_index(drawn, "square_resid"))[[1]], "zeroGrob"
  )
})

test_that("the experimental signal fires on a real call and not on a bare help call", {
  p <- gf_point(Thumb ~ Height, data = Fingers)
  f <- function(x) x + 20
  signalled <- character()
  local_mocked_bindings(
    signal_stage = function(stage, what, with = NULL, env = NULL) {
      signalled <<- c(signalled, paste0(stage, ":", what))
      invisible()
    },
    .package = "lifecycle"
  )

  suppressMessages(gf_square_resid_fun(p, f))
  expect_equal(signalled, "experimental:gf_square_resid_fun()")

  signalled <- character()
  suppressMessages(gf_square_resid_fun())
  suppressMessages(gf_square_resid_fun(p, f, show.help = TRUE))
  expect_equal(signalled, character())
})
