test_that("gf_resid_fun returns a ggplot with segment layer", {
  df <- data.frame(X = 1:10, Y = 2 + 3 * (1:10) + c(1, -1, 2, -2, 0, 1, -1, 0, 2, -2))
  my_fun <- function(x) 2 + 3 * x
  p <- gf_point(Y ~ X, data = df) %>%
    gf_function(my_fun)

  result <- suppressMessages(gf_resid_fun(p, my_fun))
  expect_s3_class(result, "ggplot")

  i <- layer_index(result, "resid")
  expect_true(inherits(result$layers[[i]]$geom, "GeomResid"))
  expect_equal(nrow(ggplot2::ggplot_build(result)$data[[i]]), nrow(df))
})

test_that("gf_resid_fun measures the residual from the observation's own x", {
  df <- data.frame(X = rep(1:3, 4), Y = seq(1, 12))
  p <- gf_jitter(Y ~ X, data = df, width = .2) %>% gf_resid_fun(function(x) x + 1)
  drawn <- ggplot2::ggplot_build(p)$data[[layer_index(p, "resid")]]

  expect_equal(drawn$yend, df$X + 1)
})

test_that("gf_resid_fun works with non-linear function", {
  df <- data.frame(X = 1:20, Y = (1:20)^2 + rnorm(20, sd = 5))
  quad_fun <- function(x) x^2
  p <- gf_point(Y ~ X, data = df)

  result <- suppressMessages(gf_resid_fun(p, quad_fun))
  expect_s3_class(result, "ggplot")
})

test_that("gf_resid_fun passes additional aesthetics", {
  df <- data.frame(X = 1:10, Y = 1:10)
  p <- gf_point(Y ~ X, data = df)
  my_fun <- function(x) x

  result <- suppressMessages(gf_resid_fun(p, my_fun, color = "red", alpha = 0.5))
  expect_s3_class(result, "ggplot")
})

test_that("gf_resid_fun reads an x mapped on the plot's first layer", {
  df <- data.frame(X = 1:10, Y = 2 + 3 * (1:10))
  p <- ggplot2::ggplot(df) + ggplot2::geom_point(ggplot2::aes(x = X, y = Y))
  r <- suppressMessages(gf_resid_fun(p, function(x) x + 1))
  drawn <- ggplot2::ggplot_build(r)$data[[layer_index(r, "resid")]]

  expect_equal(drawn$yend, df$X + 1)
})

test_that("gf_resid_fun snapshot", {
  skip_if_not_installed("vdiffr")
  df <- data.frame(X = 1:10, Y = c(3, 5, 8, 10, 14, 16, 20, 22, 25, 28))
  my_fun <- function(x) 1 + 3 * x
  p <- gf_point(Y ~ X, data = df) %>%
    gf_function(my_fun)

  suppressMessages(gf_resid_fun(p, my_fun, color = "red")) %>%
    expect_doppelganger("gf_resid_fun-basic")
})


# gf_resid_fun() is generated by ggformula::layer_factory() now, like every
# other layer in this package. These are the contract: what the generated
# function has to keep doing that the bespoke one did, and the things the
# generated one could lose in silence.

test_that("a function given positionally lands where a function given by name does", {
  # `layer_factory()` binds the second positional argument to `gformula`, and
  # `gf_resid_fun(p, f)` is the spelling in every test, example and lesson
  df <- data.frame(X = 1:10, Y = 2 + 3 * (1:10))
  p <- gf_point(Y ~ X, data = df)
  my_fun <- function(x) 2 + 3 * x

  positional <- suppressMessages(gf_resid_fun(p, my_fun))
  named <- suppressMessages(gf_resid_fun(p, fun = my_fun))

  expect_equal(layer_index(positional, "resid"), 2L)
  expect_equal(layer_index(named, "resid"), 2L)
  expect_equal(
    ggplot2::ggplot_build(positional)$data[[2]],
    ggplot2::ggplot_build(named)$data[[2]]
  )
  expect_equal(ggplot2::ggplot_build(positional)$data[[2]]$yend, my_fun(df$X))
})

test_that("a non-function is refused as a function, whichever way it is written", {
  # the recovery moves position 2 into `fun` unconditionally, with no
  # `is.function()` test: a formula that failed such a test would stay in
  # `gformula` and die inside ggformula's own formula parsing, which is a
  # different answer to the same mistake than the one this has always given
  p <- gf_point(Thumb ~ Height, data = Fingers)
  model <- lm(Thumb ~ Height, data = Fingers)

  for (bad in list(model, Thumb ~ Height, 3, "nope")) {
    expect_error(suppressMessages(gf_resid_fun(p, bad)), 'could not find function "fun"')
    expect_error(suppressMessages(gf_resid_fun(p, fun = bad)), 'could not find function "fun"')
  }
})

test_that("a function with no plot under it is refused, and a plot with no function", {
  p <- gf_point(Thumb ~ Height, data = Fingers)
  expect_error(
    suppressMessages(gf_resid_fun(fun = function(x) x)),
    "`gf_resid_fun\\(\\)` needs to be layered on top of a plot"
  )
  expect_error(
    suppressMessages(gf_resid_fun(p)),
    "`gf_resid_fun\\(\\)` needs to be told which function"
  )
})

test_that("the plot is the first argument, and a name for it is not one", {
  # `plot` was the released spelling of the first argument. It is now `object`,
  # the name every generated ggformula layer uses, so `plot =` is an unknown
  # name like any other and ggformula discards it -- which leaves no plot, and
  # the refusal a caller sees is the one for that
  p <- gf_point(Thumb ~ Height, data = Fingers)
  f <- function(x) x + 20

  expect_error(gf_resid_fun(plot = p, fun = f), "layered on top of a plot")
  expect_no_error(suppressMessages(gf_resid_fun(object = p, fun = f)))
})

test_that("a bare call prints the layer's own help instead of drawing", {
  # `pre` runs ahead of ggformula's help gate, so everything it does has to
  # survive a call with no plot and no function
  expect_message(bare <- gf_resid_fun(), "does not require a formula")
  expect_null(bare)

  p <- gf_point(Thumb ~ Height, data = Fingers)
  expect_message(asked <- gf_resid_fun(p, show.help = TRUE), "key attributes")
  expect_null(asked)
})

test_that("the labelling arguments every ggformula layer takes reach the plot", {
  p <- gf_point(Thumb ~ Height, data = Fingers) %>%
    gf_resid_fun(function(x) x, title = "TT", xlab = "XX", ylab = "YY")

  expect_equal(p$labels$title, "TT")
  expect_equal(p$labels$x, "XX")
  expect_equal(p$labels$y, "YY")
})

test_that("a residual draws with its own geom, stat and position whatever is asked for", {
  p <- gf_point(Thumb ~ Height, data = Fingers)

  expect_no_warning(
    asked <- suppressMessages(
      gf_resid_fun(p, function(x) x, geom = "segment", stat = "identity", position = "dodge")
    )
  )
  layer <- asked$layers[[layer_index(asked, "resid")]]

  expect_s3_class(layer$geom, "GeomResid")
  expect_s3_class(layer$stat, "StatResid")
  # an unjittered plot needs no offset, so the layer declares identity;
  # what matters is that the caller's `position =` did not reach it
  expect_s3_class(layer$position, "PositionIdentity")
  expect_true(isTRUE(layer$inherit.aes))
})

test_that("a stray positional argument gets ggformula's own refusal, not one of ours", {
  # the released signature was `gf_resid_fun(plot, fun, linewidth = 0.2, ...)`,
  # and the third position really worked until this conversion. The generated
  # third formal is `data`, and `pre` fills it only when the caller left it
  # alone, so a stray third argument reaches ggformula and is refused exactly as
  # it is for any other gf_ function. This package adds no rule of its own.
  p <- gf_point(Thumb ~ Height, data = Fingers)

  expect_error(gf_resid_fun(p, function(x) x, 2), "must be a <data.frame>")
  expect_error(gf_point(Thumb ~ Height, Fingers, 0.5), "must be a <data.frame>")

  # an unusable extra is silent, the same as a misspelled parameter
  expect_no_error(suppressMessages(gf_resid_fun(p, function(x) x, nonesuch = 1)))
  expect_no_warning(suppressMessages(gf_resid_fun(p, function(x) x, nonesuch = 1)))
})

test_that("the function is called on the x values the plot draws", {
  # the x quosure evaluated in the plot's own data, so a plotted expression is
  # measured as the expression rather than as the column underneath it
  p <- gf_point(Thumb ~ log(Height), data = Fingers)
  r <- suppressMessages(gf_resid_fun(p, function(x) x * 14))
  drawn <- ggplot2::ggplot_build(r)$data[[layer_index(r, "resid")]]

  expect_equal(drawn$yend, log(Fingers$Height) * 14)
})

test_that("a residual resolves an x bound to the frame the plot was written in", {
  # `gf_ingredients()` rewrites every quosure's environment to this caller's
  # frame; `resid_layer_fun()` puts the plot's own quosures back over the
  # copies, which is what keeps such a plot measurable at all
  p <- local({
    shift <- 10
    gf_point(Thumb ~ I(Height + shift), data = Fingers)
  })
  r <- suppressMessages(gf_resid_fun(p, function(x) x - 10))
  drawn <- ggplot2::ggplot_build(r)$data[[layer_index(r, "resid")]]

  expect_equal(as.numeric(drawn$yend), as.numeric(Fingers$Height))
})

test_that("the plot is reported before the function is ever called", {
  # `check_resid_axes()` runs before `fun` does, so a plot with no y and a
  # function that cannot be called reports the plot, not the function
  boom <- function(x) stop("this function cannot be called")

  expect_error(
    suppressMessages(gf_resid_fun(gf_histogram(~Thumb, data = Fingers), boom)),
    "A residual needs both an x and a y on the plot"
  )
})

test_that("a discrete x reaches the function as the factor the plot draws", {
  # the one place a function-measured residual can genuinely misbehave: the x
  # quosure evaluates to a factor, so an arithmetic function predicts NA
  # everywhere and only a function that coerces draws anything
  p <- gf_point(Thumb ~ Sex, data = Fingers)

  # ggplot2 4.0 carries the arithmetic-on-a-factor NAs through to the layer and
  # warns; 3.5.2's continuous scale refuses them before the layer is built. Both
  # reject the nonsense, at different depths, so only the version that lets it
  # reach the data can be asked what the data holds.
  # WHEN THE FLOOR MOVES TO 4.0: delete this skip.
  skip_if_not(
    utils::packageVersion("ggplot2") >= "4.0.0",
    "ggplot2 3.5.2 refuses a factor at the scale; see R/compat-ggplot2.R"
  )

  expect_warning(
    arithmetic <- ggplot2::ggplot_build(
      suppressMessages(gf_resid_fun(p, function(x) 0.5 * x))
    ),
    "not meaningful for factors"
  )
  expect_true(all(is.na(arithmetic$data[[2]]$yend)))

  coercing <- suppressMessages(gf_resid_fun(p, function(x) 40 + 10 * as.numeric(x)))
  expect_equal(
    ggplot2::ggplot_build(coercing)$data[[2]]$yend,
    40 + 10 * as.numeric(Fingers$Sex)
  )
})

test_that("an unusable name is answered the way the family the caller wrote answers it", {
  # a `gf_` function discards it in silence like `gf_point()` beneath it in the
  # pipe; a layer assembled the ggplot2 way warns on its own, because
  # `resid_layer_fun()` passes `check.param` through instead of overriding it
  p <- gf_point(Thumb ~ Height, data = Fingers)
  expect_no_warning(suppressMessages(gf_resid_fun(p, function(x) x, colr = "red")))

  fitted <- transform(Fingers, .fitted = Fingers$Height)
  expect_warning(
    ggplot2::ggplot_build(
      p + ggplot2::layer(
        geom = GeomResid, stat = StatResid, position = "identity",
        data = fitted, mapping = ggplot2::aes(yend = .data$.fitted),
        params = list(nonesuch = 1)
      )
    ),
    "unknown parameters"
  )
})
test_that("a residual stays on the point it belongs to when the plot jitters", {
  # the residual declares the same jitter the points layer carries, seed and all,
  # so both layers compute the same offsets independently. Nothing is replayed:
  # an offset is a function of the seed and the rows, and both layers have both
  set.seed(7)
  p <- gf_jitter(Thumb ~ Sex, data = Fingers, width = .2) %>%
    gf_resid_fun(function(x) 60)

  points <- ggplot2::layer_grob(p, 1)[[1]]
  segments <- ggplot2::layer_grob(p, layer_index(p, "resid"))[[1]]

  expect_equal(as.numeric(segments$x0), as.numeric(points$x))
  expect_equal(as.numeric(segments$y1), as.numeric(points$y))
})

test_that("what to draw is removed from the layer's parameters, however it was spelled", {
  # `fun` genuinely reaches the layer function in `params` when the caller wrote
  # `fun =` and not when they wrote it positionally, so the two spellings only
  # build the identical layer because this helper removes it. Handed
  # `check.param = TRUE` the removal is visible; the last two expectations are
  # the other half of the same contract -- `check.param` is passed through, not
  # overridden, so a name nothing claims warns the ggplot2 way and is silent the
  # ggformula way.
  aes0 <- ggplot2::aes(yend = .data$.fitted)
  build <- function(params, check.param) {
    coursekata:::resid_layer_fun("resid", aes0)(
      GeomResid, StatResid, "identity",
      params = params, mapping = aes0,
      data = transform(Fingers, .fitted = Fingers$Height),
      check.param = check.param
    )
  }

  expect_no_warning(build(list(fun = function(x) x, linewidth = 0.2), TRUE))
  expect_no_warning(build(list(model = lm(Thumb ~ Height, data = Fingers)), TRUE))
  expect_warning(build(list(nonesuch = 1), TRUE), "unknown parameters")
  expect_no_warning(build(list(nonesuch = 1), FALSE))
})

test_that("the experimental signal fires on a real call and not on a bare help call", {
  # the one contract no fingerprint can see: `lifecycle::signal_stage()` emits
  # nothing observable at 1.0.5, so a mocked binding is the only gate on where
  # the signal sits -- behind the help gate, and first inside it
  p <- gf_point(Thumb ~ Height, data = Fingers)
  f <- function(x) x + 20
  signalled <- character()
  local_mocked_bindings(
    signal_stage = function(stage, what, with = NULL, env = NULL) {
      signalled <<- c(signalled, paste0(stage, ":", what))
      invisible()
    },
    .package = "lifecycle"
  )

  suppressMessages(gf_resid_fun(p, f))
  expect_equal(signalled, "experimental:gf_resid_fun()")

  # a call that is about to be refused is still a call
  signalled <- character()
  try(suppressMessages(gf_resid_fun(Fingers, f)), silent = TRUE)
  expect_equal(signalled, "experimental:gf_resid_fun()")

  # asking a function what it takes is not using it
  signalled <- character()
  suppressMessages(gf_resid_fun())
  suppressMessages(gf_resid_fun(p, f, show.help = TRUE))
  expect_equal(signalled, character())
})

test_that("a function that predicts nothing for a row drops that row and says so", {
  # `GeomResid$handle_na` names the end that arrived, because the inherited drop
  # reads `required_aes` literally and `"xend|yend"` is not a column
  p <- gf_point(Thumb ~ Height, data = Fingers)
  drawn <- suppressMessages(gf_resid_fun(p, function(x) ifelse(x > 65, NA_real_, 60)))

  expect_warning(
    grob <- ggplot2::layer_grob(drawn, layer_index(drawn, "resid"))[[1]],
    "geom_resid"
  )
  expect_equal(length(grob$x0), sum(Fingers$Height <= 65))
})
