on:
  push:
    branches:
      - main
      - release/*
      - hotfix/*
    paths-ignore:
      - "*.md"
      - "*.Rmd"
      - ".vscode/**"
  pull_request:
    branches:
      - develop
      - release/*
      - hotfix/*
    paths-ignore:
      - "*.md"
      - "*.Rmd"
      - ".vscode/**"
  workflow_dispatch:

name: Test non-interactive

jobs:
  test:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: macOS-latest, r: "release" }
          - { os: windows-latest, r: "release" }
          # - { os: windows-latest, r: "3.6" } the cli::rule dashes get messed up
          - { os: ubuntu-latest, r: "devel", http-user-agent: "release" }
          - { os: ubuntu-latest, r: "release" }
          - { os: ubuntu-latest, r: "oldrel-1" }

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v3

      # https://github.com/r-lib/actions/tree/v2/setup-pandoc
      - uses: r-lib/actions/setup-pandoc@v2

      # https://github.com/r-lib/actions/tree/v2/setup-r
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      # https://github.com/r-lib/actions/tree/v2/setup-r-dependencies
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::devtools
          needs: check

      - name: Install the package
        run: Rscript -e 'devtools::install()'

      - name: Test loading in non-interactive mode (normal)
        run: Rscript bin/load-non-interactive.r

      - name: Test loading in non-interactive mode (quiet)
        run: Rscript bin/load-non-interactive-quiet.r

      - name: Test loading in non-interactive mode (quickstart)
        run: Rscript bin/load-non-interactive-quickstart.r
